### ISSUE TITLE
Is there an example of a basic setup?

### ISSUE THREAD

**Issue by cbmeeks** [bzotto/MCS6502#2]
Hello.  I just came across your emulator and was curious on how to use it.  I'm a Java developer and it's been a *long* time since I've been active in C.

I'm struggling with the basic setup.

Here is what I have at the moment:

        int init6502(void) {
            MCS6502ExecutionContext context;
            MCS6502Init(&context, readBytesFn, writeBytesFn, NULL);  // Final param is optional context.
            MCS6502Reset(&context);
            MCS6502Tick(&context);

            return 0;
        }

        uint8 readBytesFn(void) {
            printf("Reading bytes...\n");
            return 0x00;
        }

        void writeBytesFn(void) {
            printf("Writing bytes...\n");
        }

I'm getting warnings on incompatible types such as:

      warning: passing argument 2 of ‘MCS6502Init’ from incompatible pointer type [-Wincompatible-pointer-types]
         21 |     MCS6502Init(&context, readBytesFn, writeBytesFn, NULL);  // Final param is optional context.
            |                           ^~~~~~~~~~~
            |                           |
            |                           uint8 (*)(void) {aka unsigned char (*)(void)}
      In file included from src/crabapple.c:6:

Would you happen to have an example of just this basic setup?

Thanks!

**Comment by bzotto** [comment]
Hey there, glad you're giving it a spin. C is going to want the function signatures to match what the typedefs specify or it'll be unhappy. The read and write functions are designed to read a byte given an address, and write a byte value given an address. Both functions also must accept the context pointer in case that's useful (though it might well not be). So the read and write functions should have these signatures:

```
uint8 SampleReadFuction(uint16 addr, void * context) {
    // your code here; return the byte value that corresponds to the addr. you must return *something*
}

void SampleWriteFunction(uint16 addr, uint8 byte, void * context) {
    // your code here; store the byte value in whatever you're using to keep memory data. no return value.
}

```

Hope that helps get you started! 
Ben

**Comment by cbmeeks** [comment]
Thank you!  That worked.

I may have more questions soon.  But I don't want to bother.
Do you have any more documentation or tutorials?

Thanks again.

**Comment by bzotto** [comment]
Unfortunately this is all there is! But really once you have it set up it should really “just work” as a black box emulator. As far as what to do with a running 6502, there are tons of tutorials and documentation out there about how that processor works and how a (say) Apple II memory map would be set up. If you have any challenges with getting the emulator up and running though feel free to ask here !
